name: android

# build on c/cpp changes or workflow changes
on:
  push:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'po/**.po'
      - 'android/**'
      - 'builtin/**'
      - '.github/workflows/android.yml'
  pull_request:
    paths:
      - 'lib/**.[ch]'
      - 'lib/**.cpp'
      - 'src/**.[ch]'
      - 'src/**.cpp'
      - 'irr/**.[ch]'
      - 'irr/**.cpp'
      - '**/CMakeLists.txt'
      - 'cmake/Modules/**'
      - 'po/**.po'
      - 'android/**'
      - 'builtin/**'
      - '.github/workflows/android.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v6
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends gettext apksigner
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
          distribution: 'temurin'
          java-version: '17'
    - name: Generate debug keystore
      run: |
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Debug, OU=Debug, O=Debug, L=Debug, S=Debug, C=US"
    - name: Build AAB with Gradle
      run: cd android; ./gradlew bundlerelease
    - name: Build APKs with Gradle
      run: cd android; ./gradlew assemblerelease
    - name: Sign APKs
      run: |
        cd android/app/build/outputs/apk/release
        for apk in *-unsigned.apk; do
          signed_name="${apk/-unsigned/}"
          apksigner sign --ks ../../../../../debug.keystore --ks-pass pass:android --key-pass pass:android --out "$signed_name" "$apk"
        done
    - name: Save AAB artifact
      uses: actions/upload-artifact@v5
      with:
        name: Luanti-release.aab
        path: android/app/build/outputs/bundle/release/app-release.aab
    - name: Save armeabi artifact
      uses: actions/upload-artifact@v5
      with:
        name: Luanti-armeabi-v7a.apk
        path: android/app/build/outputs/apk/release/app-armeabi-v7a-release.apk
    - name: Save arm64 artifact
      uses: actions/upload-artifact@v5
      with:
        name: Luanti-arm64-v8a.apk
        path: android/app/build/outputs/apk/release/app-arm64-v8a-release.apk
    - name: Save x86 artifact
      uses: actions/upload-artifact@v5
      with:
        name: Luanti-x86.apk
        path: android/app/build/outputs/apk/release/app-x86-release.apk
    - name: Save x86_64 artifact
      uses: actions/upload-artifact@v5
      with:
        name: Luanti-x86_64.apk
        path: android/app/build/outputs/apk/release/app-x86_64-release.apk
